name: Build and Push Gemoe Image

on:
  push:
    paths:
      - "Gemoe/Dockerfile"
      - "Gemoe/setup"

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Build and Push Image

    runs-on: ubuntu-26.04

    steps:
      - name: Login to Docker.io
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          tags: |
            gemoe
          images: |
            arakurumi/bot
          labels: |
            org.opencontainers.image.authors=Kurumi <kqruumi@gmail.com>
            org.opencontainers.image.description=Docker Images for My Bot
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=Docker-Bot
            org.opencontainers.image.version={{date 'YYYYMMDD'}}

      - name: Build and Push to Docker.io
        uses: docker/build-push-action@v7
        with:
          push: true
          context: "{{defaultContext}}:Gemoe"
          no-cache: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
